### ISSUE TITLE
Wrap existing content into 12 col element

### ISSUE THREAD

**Issue by madc** [Frontwise/grid-editor#10]
Here is the scenario: If you apply the grid editor to a text field that is already pre-populated with (non-bootstrap formated) content, this content can't be edited.

Do you think, it is possible/a good idea to auto-wrap this content into a 12 col bootstrap row?

**Comment by Epskampie** [comment]
Yes, that seems like a good suggestion that would make the plugin more robust. As long as we can find a bulletproof way to detect wether the content is "non-bootstrap formatted" as you put it.

Feel free to get started on a pull request, otherwise I will start on it when I've got time.

**Comment by Epskampie** [comment]
This functionality is now included, update to [v0.1.0](https://github.com/Frontwise/grid-editor/tree/0.1.0) to get it.

**Comment by madc** [comment]
That's great! I'll give it a spin later this week.

You might want to consider to remove the [console.log](https://github.com/Frontwise/grid-editor/blob/master/src/js/jquery.grideditor.js#L34) on line 34.. ;)

**Comment by Epskampie** [comment]
Haha, yeah, that one slipped through. Good to hear that it's working for you.
