### ISSUE TITLE
Remove editor

### ISSUE THREAD

**Issue by jktb75** [Frontwise/grid-editor#102]
Love your editor. Please keep up the amazing work.

I added a button that removes the editor once the user is done editing and it works great on first page, however it doesn't work on other pages that open as tabs. This is what I've done for the button:
$(".btnSubmit2").click(function(){
           var html = $('.ge-canvas').gridEditor2('remove');
 }); 

Please help. Thank you

**Comment by Epskampie** [comment]
I don't see how/why it would work differently on pages that open as tabs.
