### ISSUE TITLE
Content locked position 

### ISSUE THREAD

**Issue by daslicht** [Frontwise/grid-editor#11]
It would be nice if the content would stay at the exact same position when you switch to preview.
Currently it jumps happily around :)

**Comment by Epskampie** [comment]
I agree this would be really nice. However, the editor GUI also needs space, especially if it is to be as clear and simple as it is right now.

Simply hiding all the editor GUI for preview is also not acceptable, as the preview will then not match the final design.

It might be possible to just show GUI on hover, with row buttons sticking out to the left, and column buttons sticking out to the top, so no extra space is needed. However, I still think it would cause problems  with overlapping buttons, especially when you are multiple levels deep... 

Any suggestions on how to solve this problem?

**Comment by daslicht** [comment]
I just started with Grid Editor, so maybe I come up with a solution soon.
How about positioning the GUI elements outside the flow, for example relative positioned.
That way they content would not care about either they are present or not :)

**Comment by daslicht** [comment]
I quickly hacked the css in the browser and came up with this:
http://screencast.com/t/CVD4ORNr0O

However that only works for one row so far :)

**Comment by Epskampie** [comment]
Haha, nice hack, that does seem to work a bit already!
For me to merge it though, it would have to be as clear to the user as it is now (where do rows start/end), what am i actually editing if I click here, and as flexible (always work well, even when multiple layers of rows and columns are nested).

Nice work though, keep it up and you might just get there. Thanks for sharing!

**Comment by daslicht** [comment]
I keep experimenting, but I think you solution is already the best.

**Comment by Epskampie** [comment]
Let me know if you come up with something.
