### ISSUE TITLE
Uncaught TypeError: tinymce.DOM.uniqueId is not a function

### ISSUE THREAD

**Issue by daslicht** [Frontwise/grid-editor#12]
Hi,
I just added the Grid-Editor you my test (WordPress) project, it shows up but when I click some text I get : 

```
Uncaught TypeError: tinymce.DOM.uniqueId is not a function
```
Standalone its working of course , so its not an issue with your PlugIn, but it would be useful for me if you have encountered that error in some combination previously.

**Comment by daslicht** [comment]
I tried removing : 
```
 content_types: ['tinymce'],
```
But I still get that error? So TinyMCE will always get hooked to grid-editor even if I dont add : 
 content_types: ['tinymce'],
?

**Comment by daslicht** [comment]
Ok some new insights !
Its working with the following Versions:
```
    <script src="https://tinymce.cachefly.net/4.0/tinymce.min.js"></script>
    <script src="https://tinymce.cachefly.net/4.0/jquery.tinymce.min.js"></script>
```
but not with the actual versions on bower:
```
 "version": "4.2.6",
```

**Comment by Epskampie** [comment]
Thanks for looking into this, I will check into the bower the depenceny / update to work with the newest tinymce. For the record:

- TinyMCE version 4.2.6 is not working, but 4.0 is?
- What browser are you using?

**Comment by daslicht** [comment]
Those are my inspections so far yes.

**Comment by daslicht** [comment]
How would I need to start to add http://summernote.org/#/ instead of TinyMCE ? Please?

**Comment by Epskampie** [comment]
You should start by using the gridEditor without the TinyMCE plugin included [from the src directory](https://github.com/Frontwise/grid-editor/tree/master/src/js)
Then you should write a plugin that works similarly to [jquery.grideditor.tinymce.js](https://github.com/Frontwise/grid-editor/blob/master/src/js/jquery.grideditor.tinymce.js)

If you do so, I would be very interested in a pull request that adds the new plugin. :)

**Comment by daslicht** [comment]
Ok i am on it :) 
I am a lil' bit confused (no xp in that) by the following:

https://github.com/Frontwise/grid-editor/blob/master/src/js/jquery.grideditor.tinymce.js#L22
```
              var configuration = $.extend(
                        (settings.tinymce && settings.tinymce.config ? settings.tinymce.config : {}),
                        {
                            inline: true,
                            oninit: function(editor) {
                                try {
                                    settings.tinymce.config.oninit(editor);
                                } catch(e) {}
                                $('#'+editor.settings.id).focus();
                            }
                        }
                    );
                    var tiny = contentArea.tinymce(configuration);
```
Do I understand it correct that you do the following:
Check if ```settings.tinymce``` and ```settings.tinymce.config``` is present
If not just extend the configuration with an a empty object

But where is this oninit function coming from?
And where does the passed variable ```editor``` comes from ?

**Comment by daslicht** [comment]
Here we go : 
https://dl.dropboxusercontent.com/u/75681914/code/grid-editor/example/summernote.html

**Comment by daslicht** [comment]
NO BUG !
I got it working with the latest download version : 
*TinyMCE 4.2.7 jQuery package*
Even the Integration of elFinder is working ! 
AwESoME!

**Comment by daslicht** [comment]
I will do further tests in conjunction with Wordpress, probably the error was related to a conflikt with the TinyMCE version of Wordpress?!

**Comment by Epskampie** [comment]
Well, you do need the tinyMCE jquery integration plugin. This is written in the readme as well: 
`If you want to use the tincyMCE integration, load tinyMCE en tinyMCE jQuery plugin as well.`

So that may have been the problem with your previous tinymce 4.2.6 as well. :) I will upgrade the bower file to properly reflect this.

**Comment by daslicht** [comment]
Yeah I have used that integration plug.

**Comment by daslicht** [comment]
->>> http://5.45.104.102/dev/grid-editor/example/tinymce.html :dancer:

**Comment by Epskampie** [comment]
As you can see I've updated the plugin to tinyMCE 4.2.7, and as you've already concluded, it works :-)
https://transfer.frontwise.com/frontwise/grid-editor/example/

I see that the summernote plugin example you made is now offline, would you consider making a pull request for the integration plugin, so that others can benefit from your work?

**Comment by daslicht** [comment]
I haven't made a pull request yet because the Summenote version on the cdn (buggy) is not up-to date . I thought it was no good idea that we would need to include summernote. What do you think?

**Comment by daslicht** [comment]
How would I make a PullRequest for just that file : 
https://github.com/daslicht/grid-editor/blob/master/src/js/jquery.grideditor.summernote.js

**Comment by daslicht** [comment]
Just created a Pull Request
