### ISSUE TITLE
How to add plugin in TinyMCE with  ?

### ISSUE THREAD

**Issue by EliosFlorian** [Frontwise/grid-editor#14]
Is it possible to customize tinyMCE jQuery plugin with plugin functions like "code" or "colorpicker" button ?

**Comment by daslicht** [comment]
Yes it is possible but you need to include the TinyMCE PlugIns and add the colorPicker to the Plugin Settings.
My for might be helpful:
https://github.com/daslicht/grid-editor/blob/master/src/js/jquery.grideditor.tinymce.js#L30

**Comment by Epskampie** [comment]
You can specify tinyMCE options using the tinymce.config option. I added documentation for this, see: `tinymce.config` under [options](https://github.com/Frontwise/grid-editor#options).

**Comment by daslicht** [comment]
Yeah thats even better :+1:
