### ISSUE TITLE
Using CKEditor, possible?

### ISSUE THREAD

**Issue by zotalegre** [Frontwise/grid-editor#15]
Hi! Are there some tips on CKEditor replacing tinyMCE? Thanks

**Comment by Epskampie** [comment]
Yeah, please refer to [my comment here](https://github.com/Frontwise/grid-editor/issues/12#issuecomment-151617410) to learn how to write a plug-in that integrates a new text editor.

**Comment by Epskampie** [comment]
Hope this gives you enough to work with. Please consider making a pull request if/when you make a plugin, so that others can benefit from your work!
