### ISSUE TITLE
Full width editor

### ISSUE THREAD

**Issue by lianee** [Frontwise/grid-editor#19]
Really nice work, Would it be possible to extend it to a full width editor?

By that, I mean to edit full width rows used to display various backgrounds, then a container to adapt the real content to the device, then the usual real rows and columns.

For Bootstrap, the markup looks something like that:

```HTML
<div class="container-fluid class-first-part" style="background-color:#000;color:#fff"><!-- most outer part, used for visual effect -->
  <div class="container"><!-- sets the width depending of device -->
    <div class="row"><!-- here starts the real content -->
      <div class="col-lg-6">lorem ipsum</div>
      <div class="col-lg-6">lorem ipsum</div>
    </div>
  </div>
</div>
<div class="container-fluid class-second-part" style="background-color:#fff;color:#000"><!-- next visual block, different background -->
  <div class="container">
    <div class="row">
      <div class="col-lg-4">lorem ipsum</div>
      <div class="col-lg-4">lorem ipsum</div>
      <div class="col-lg-4">lorem ipsum</div>
    </div>
  </div>
</div>
```

The outside "container-fluid" blocks could be re-ordered, and should have a set of specific options.

This could probably be achieved with a "container editor" managing the container blocks, each wrapping a grid-editor inside

**Comment by Epskampie** [comment]
Thanks!

I would suggest adding "container" as a possible class on rows (click the gear icon on a row), then maybe adding some css to fix the issues that are caused by the div being both a row and a container.

Anyway, I'm afraid I don't think that I will extend grid editor support "container" elements, as it is outside it's scope.
