### ISSUE TITLE
The drag and drop is hard to control

### ISSUE THREAD

**Issue by onigetoc** [Frontwise/grid-editor#26]
The drag and drop is hard to control, need a better smoother drag.

When adding new row or grid from the top, should be draggable too and put it where we want.

Why it's not fluid like that? http://jsfiddle.net/vaibviad/fHSBg/176/

**Comment by Aris-haryanto** [comment]
You mean like this check this out in my fork https://github.com/Aris-haryanto/grid-editor

**Comment by Epskampie** [comment]
I've stopped hiding the element being dragged during the drag. This makes it a bit better visually, although the dragging still has room for improvement.

**Comment by onigetoc** [comment]
@Aris-haryanto 
Perfect, you should push this here to this project.
And i had the same idea for the add/clone button, 
another + button was confusing.

**Comment by onigetoc** [comment]
TODO.
1 - Download HTML button with FIlesaver.js.
2 - don't like this preview mode on mouse hover.
3 - Drag new column maker where you want.
add more feature to drag "Button, nav header Jumbo, image ect....."

**Comment by onigetoc** [comment]
@Aris-haryanto You seem to be active of this project. do you want to work with me on this?
I want to drag many element like i said in my TODO list.
Email me from my website if you are interested.
http://softplug.com/contact-us/
