### ISSUE TITLE
how to make it save able into file or database?

### ISSUE THREAD

**Issue by onnosilaban** [Frontwise/grid-editor#28]
hi masters, i'm a newbie, this is looks like a great script, but i don't have any idea to save it, is there any body can help me please?

**Comment by ddegil** [comment]
Like in the demo, make a call to $('[editor]').gridEditor('getHtml'). Depending on your page language, you can set a catch to the post button and then call the script and populate a hidden input with the results. Then get the value from the input on the other side.

**Comment by anilkuchana1** [comment]
Hi,
Pl advise how do I display the saved grid ??

**Comment by f1nnix** [comment]
@anilkuchana1 just display it unescaped.
