### ISSUE TITLE
Name field in bower.json and publish as a bower package.

### ISSUE THREAD

**Issue by kamalkhan** [Frontwise/grid-editor#3]
Great work. It would be nice to allow consuming it as a package via bower install. 

To recognise this as a bower package could you:

1. Modify the name field in bower.json from Grid Editor to grid-editor (no spaces).
2. Run `bower register grid-editor git://github.com/Frontwise/grid-editor.git` in terminal from your end to publish this as a bower package.

Thank you

**Comment by Epskampie** [comment]
Thanks for bringing this to my attention. It is done.
