### ISSUE TITLE
use in bootstrap tab

### ISSUE THREAD

**Issue by heikobihlmaier** [Frontwise/grid-editor#30]
Using in Bootstrap Tab is currently not possible, because all controls are at the last tab

How can i correct this ?

**Comment by ddegil** [comment]
I am using it with bootstrap tabs just fine. I just took my output html from .net and stripped out what is not needed and put image placeholders in. There are 4 tabs, one has 4 tinymce editors and the grid-editor is used in the content tab. My actual page has a lot more and navigation and command buttons after the tab-content, so the are always usable.

This is a self-contained file. Just pull it from the zip and see it work. I have verified it working in MS IE10, MS Edge, Firefox and chrome.

Sincerely,

David

[bstabs.zip](https://github.com/Frontwise/grid-editor/files/107383/bstabs.zip)
