### ISSUE TITLE
How to make the source textarea always up to date with the code on every activity ?

### ISSUE THREAD

**Issue by semplon** [Frontwise/grid-editor#36]
As the title above, i want to update the source textarea on every add or remove grid, or update the content inside it. So without clicking the source button the textarea is up to date with the grid code.

is it possible ? how to do that ?

thanks,

**Comment by Aris-haryanto** [comment]
i have added copy function here https://github.com/Aris-haryanto/grid-editor
is this what you mean ?

**Comment by semplon** [comment]
i'll try it, thanks in advance.

**Comment by semplon** [comment]
this is not what i mean. see this video for detail https://youtu.be/DUUYXCplpqo

it won't save the value since the textarea didn't get the html value of the canvas. it will save the value when we click the html button. all i need is when we editing the layout, the textarea should be changed as well. 

any idea how to do this ?

**Comment by semplon** [comment]
i think i've figure it out.

thanks

**Comment by 2braincells2go** [comment]
@semplon Do you mine sharing how you solved the issue? Having same and can't seem to get working solution.

Thanks!

**Comment by semplon** [comment]
@2braincells2go i add save button at the grid toolbar, it will save the current grind into the summernote editor.
