### ISSUE TITLE
Infinite loop when you pass a summernote configuration.

### ISSUE THREAD

**Issue by JordiStc** [Frontwise/grid-editor#37]
There is an infinite loop when you pass a summernote configuration.
I suppose that the idea is to call onInit from the "extended configuration" but now is calling their own callbacks.onInit endless

**Comment by naimkhalifa** [comment]
I'm also trying to customize summernote settings with grid-editor. But as it's not documented at all, it's a bit hard to understand how this works without diving into source code. It'd be wonderful if you had a small code snippet to share on this topic.

**Comment by Epskampie** [comment]
Thanks for reporting. This is now fixed. 

See the summernote example for a small code snippet, whatever you pass in their is just the normal summernote config: http://summernote.org/deep-dive/
