### ISSUE TITLE
Could not find facility which can set grid system as per device

### ISSUE THREAD

**Issue by dhwalin** [Frontwise/grid-editor#38]
When user make four columns for example & want to set **_col-lg-4 col-md-4 col-sm-6 col-xs-12_** for those all, could not. By default it is taking col-lg-4 col-md-4 col-sm-4 col-xs-4.

Yes we can do from source code. But if you can bring that handy, appreciable

**Comment by jakobjh** [comment]
I agree that this is a problem. Normally I only set col-md-4 if I want 3 equal columns. And then when displayed on a mobile device by standard the columns are shown on top of each other which is fine. 
But when using this grid-editor col-sm-4 and col-xs-4 are automatically added for every column which means it shows the 3 columns also on a extra small screen and this does not look good. 
Then I have to manully edit all code in code-view mode. And if you dont know anything about bootstrap this is a problem. (e.g. my customers..)

**Comment by Epskampie** [comment]
I don't get this issue. You don't have to edit code, you can select `tablet` or `phone` at the top right, and any change you make will only reflect that screen-size.

**Comment by jakobjh** [comment]
Ahh okay. I didn't know you could actually use that and make changes for the different screen sizes this way. Great. Then there is no issue anymore:)
