### ISSUE TITLE
How to get blocks coordinates?

### ISSUE THREAD

**Issue by marat-chardymov** [Frontwise/grid-editor#39]
Correct me if I'm wrong, but I see only one method in grideditor - 'getHtml'. Is there a way to get blocks coordinates as json? Something like [[12], [6,6], [9,3]] but after user has changed blocks position

**Comment by Epskampie** [comment]
You're right, there isn't any method to get this right now. You could try extracting this information the generated HTML with jQuery, as it has a fixed structure with rows, and columns inside those rows (and sometimes more rows inside those columns, etc. :-) )

I don't think it's really a function the grid editor should have, so I don't consider implementing it.

**Comment by Epskampie** [comment]
You're right, there isn't any method to get this right now. You could try
parsing the generated HTML, as it has a fixed structure with rows, and
columns inside those rows (and sometimes more rows inside those columns,
etc. :-) )

I don't think it's really a function the grid editor should have, so I
don't consider implementing it.

>

**Comment by marat-chardymov** [comment]
ok, thanks) wrote such function by my self
