### ISSUE TITLE
Get resulting html

### ISSUE THREAD

**Issue by madc** [Frontwise/grid-editor#4]
I've been browsing through the code, but i can't figure out, how to get the resulting HTML code without all the clutter. `deinit` is not accessable from outside the plugin and with `.html()` i get everything including all the controls and grideditor classes.

**Comment by madc** [comment]
For now, i added this function to the plugin:

````
        self.getContent = function() {
            deinit();
            var content = canvas.html();
            init();

            return content;
        }
````

Let me know, if there is a better way, otherwise, i could prepare a PR.

**Comment by Epskampie** [comment]
Hi, thanks for bringing this to my attention, this functionality was sorely missing.
I've added a method for this along the lines of the function you posted. See https://github.com/Frontwise/grid-editor#methods
