### ISSUE TITLE
Insert container and other elements out of the rows 

### ISSUE THREAD

**Issue by lucabartoli** [Frontwise/grid-editor#40]
Is it possible to insert containers around rows? The purpose would be to have full width and boxed elements.
Another question: if I load a template injecting html, all non-rows elements are not editable. is it possible to activate the editor in these elements?

**Comment by Epskampie** [comment]
You can insert a new row and drag the blocks in there.

For the second question, just add `.row` classes beforehand using jquery.

**Comment by edwardteach42** [comment]
Update,

I added a button to each row allowing a container to be toggled on the row.  In order to accomplish this you need to:

add this to you GE config: 

```
row_tools: [{
	title: 'Container',
	iconClass: 'glyphicon-inbox',
	className: 'add-container',
	on: {
		click: function() {
			if ($(this).closest('.row.ui-sortable').parent('.container.ge-container').length) {
				$(this).closest('.row.ui-sortable').unwrap();
				$(this).css('color', '');
			} else {
				$(this).closest('.row.ui-sortable').wrap('<div class="container ge-container"></div>');
				$(this).css('color', 'green');
			}
		}
	}
}]
```

then add this css snippet to your css to prevent the editor from sizing the containers weird:

```
#contentRow .container {
      padding: 0;
      width: auto;
}
```

Lastly, you can add this js to the page to toggle the container buttons on page load
```
$(document).ready(function(){
    $.each( $(".add-container"), function() {
        if ($(this).parent('.ge-tools-drawer').parent('.row.ui-sortable').parent('.container.ge-container').length) {
            $(this).css('color', 'green');
        }else{
            $(this).css('color', '');
        }
    });
});
```
