### ISSUE TITLE
Question about CKEditor please...

### ISSUE THREAD

**Issue by 2braincells2go** [Frontwise/grid-editor#42]
First, very nice job on grid editor! We are dissecting it in classroom for project.

Far from CKEditor power user and cannot seem to find docs about saving the content created by grid editor. From what I have read so far at ckeditor about saving, can't seem to grasp how to implement with grid editor.

Do you (or anyone) know of good online tutorial where we might learn about saving with layout such as grid editor?

Appreciate any input.

Woody

**Comment by Epskampie** [comment]
Did you check the example? https://github.com/Frontwise/grid-editor/blob/master/example/index.html

**Comment by 2braincells2go** [comment]
Yes sir, did check the example and never got grid example to save content. Something I am doing wrong for sure. Have not given up and will get back around to getting to work.

Thanks!

**Comment by Epskampie** [comment]
If you look at this piece of code:

            // Get resulting html
            var html = $('#myGrid').gridEditor('getHtml');
            console.log(html);

Afterwards the html is in the `html` variable. You can then send it to the server with a ajax request for example:

    $.ajax({
        url: 'http://example.com/save_article',
        method: 'POST',
        data: {
            html: html
        },
        error: function() {
            console.log('error while saving!')
        },
        success: function() {
            console.log('success while saving!')
        }
    })

You could write a plugin for CKeditor to add a "save" button, that does this procedure.

This should be the general way to go, good luck!

**Comment by 2braincells2go** [comment]
Thank you again @Epskampie . That tip may just get me where need to be.
