### ISSUE TITLE
Row/Col Delete Confirmation

### ISSUE THREAD

**Issue by macrodesignuk** [Frontwise/grid-editor#43]
Not an issue, but something I've added to my own code after accidentally clicking the trash icon several times. This adds a confirmation box when clicking the trash icon for row/col.

```
                createTool(drawer, 'Remove row', '', 'glyphicon-trash', function() {
                    if(confirm('Delete row?')){
                        row.slideUp(function() {
                            row.remove();
                        });
                     }
                });
```

 ```
               createTool(drawer, 'Remove col', '', 'glyphicon-trash', function() {
                    if(confirm('Delete Column?')){
                        col.animate({
                            opacity: 'hide',
                            width: 'hide',
                            height: 'hide'
                        }, 400, function() {
                            col.remove();
                        });
                     }
                });
```

**Comment by Epskampie** [comment]
Thanks, good suggestion, will add.

**Comment by bbashy** [comment]
Has a lot of issues with this saying `confirm is not a function`. Had to switch it out for Sweetalert anyway.

**Comment by Epskampie** [comment]
That must be an issue in your code, because as you can check in the console, every browser has `window.confirm` defined. 

You must have redefined `confirm` as something else by accident.

**Comment by bbashy** [comment]
Makes sense. I do use this to define dynamic alerts
```
var confirm = {
    //
}

confirm.init();
```

**Comment by Epskampie** [comment]
Ah, ok, i've changed the code to use `window.alert` so that these kinds of conflicts with local variables cannot happen. Although it is strange, I guess you were changing code inside of the grideditor code?

**Comment by bbashy** [comment]
The confirm var is in a different file completely but yeah, I shouldn't of called it `confirm` really :P

I've had to copy the source and modify it myself to use Sweetalert because the basic JS confirm is ugly. Thanks for updating it for others though :)

**Comment by Epskampie** [comment]
Ah, I guess even though you were in another file, you still overwrote `window.confirm`. In that case the fix won't do you, or anyone else, any good. Well, I tried. :-)
