### ISSUE TITLE
Save image on server instead of in database

### ISSUE THREAD

**Issue by jakobjh** [Frontwise/grid-editor#48]
Hi. 
I am using your script together with Summernote and i need to upload image to a server instead of to a database. 
Therefore I use the inUploadImage function from Summernote. Its working fine in a "clean" summernote editor. But how can i implement that in the grid-editor? I guess I should use the config setting like this:
config: {
 callbacks: {
  onImageUpload: function(files, editor, $editable) {
   sendFile(files[0],editor,$editable);
  }  
 }
}
But this is not working. Do you know a smart solution for that?
Thanks.
Jakob

**Comment by Epskampie** [comment]
The summernote in this project works the same as normal summernote. Maybe update the summernote version, as it is kind of old.

**Comment by jakobjh** [comment]
As I said, there is no problem with upload if i use it in a normal summernote project. However i use your grid-editor with summernote as content-type, then i wonder were i can use the Summernote Callback function? Is that in the Config part of the grid-editor ? (summernote.config)

**Comment by jakobjh** [comment]
In generel it seems that the "config" part of the grid-editor is not integrated well with the Summernote options. Tried for instance to set the fontnames and toolbar. None of them are working. So I think there is something missing with integrating the options from Summernote to the Grid-editor when using this as the grid-editor content_types.

**Comment by Xeronzz** [comment]
hey, for anyone still having this problem: I had the same exact problem with Summernote. In the end I've edited the jquery.grideditor.js file at the summernote area (around row 679).

There I added the callback:
onImageUpload: function(files, editor, welEditable) {
	  data = new FormData();
	  data.append("file", files[0]);
	  $.ajax({
	      data: data,
	      type: "POST",
	      url: "/base/ajax/summernoteimg.php",
	      cache: false,
	      contentType: false,
	      processData: false,
	      success: function(url) {
	          contentArea.summernote('insertImage', url);
	      }
	  });
}

After that it is uploading again and inserting the image like it should. Keep in mind I also updated Summernote, the old one had a different insertImage function.

**Comment by Epskampie** [comment]
Hey, turns out there was an issue with grid-editor clobbering user-defined summernote callbacks. You might want to give the newest version a shot, that should be fixed now.
