### ISSUE TITLE
setting ID values does not work

### ISSUE THREAD

**Issue by edrooney** [Frontwise/grid-editor#49]
Noticed in my own implementation that setting ID values for rows or columns does not work. I figured I did something wrong, but then I checked the demo and it's broken there, too. Anyone know the fix for this?

**Comment by Epskampie** [comment]
What do you mean? There is no option for setting ID's on rows or columns. You have to be more specific, post some code maybe.

**Comment by edrooney** [comment]
![image](https://cloud.githubusercontent.com/assets/1117378/25871312/16733b84-34d5-11e7-960b-75a6434cb609.png)

In the demo it appears to offer a place to input an ID as well as classes. Classes work but IDs do not. If I manually add an ID into the source preview it pulls it into the visual editor, but setting an ID in the editor does not place it into the source code.

**Comment by harkor** [comment]
I confirm.

**Comment by Epskampie** [comment]
Fixed by pr #54
