### ISSUE TITLE
Grid Editor clobbers Summernote callbacks – fixed

### ISSUE THREAD

**Issue by PlushNinja** [Frontwise/grid-editor#52]
A recent fix addressed an infinite loop with Summernote onInit, but another issue remains. If there are other callbacks defined, like onImageUpload, they are not carried over to GridEditor's Summernote instances.

I solved this with a monkey patch to jquery.grideditor.summernote.js, line 20:

    var configuration = $.extend(true, // deep copy

Specifying deep copy mode retains any callbacks you have in your Summernote config.

**Comment by Epskampie** [comment]
Good catch and solution, thanks for reporting!
