### ISSUE TITLE
Safari click issues on action bar

### ISSUE THREAD

**Issue by Xeronzz** [Frontwise/grid-editor#56]
Hi there! When you use the script in combination with summernote and OSX Safari the action bar popup which shows when you select something isn't clickable.
Whenever you click a button (bold, italic, ..) the action bar just disappears without any changes.

If I try the same in Chrome it is working as intended. Would you know any fix for this in Safari?
It also occurs on the Summernote example page.

Thanks in advance.

**Comment by Xeronzz** [comment]
I see it is an Summernote issue, so this can be closed.
It also happens at the Airmode on the summernote preview page.

**Comment by Epskampie** [comment]
Ok, thanks for investigating further.
