### ISSUE TITLE
No cleaned html

### ISSUE THREAD

**Issue by WebCustoms** [Frontwise/grid-editor#59]
Hi,

i use your plugin, very cool, but unfortunately I don't get a clean html with this method getHTML.
In the markup are still div containers, with the classes "get-content".

Example:
`<div class="ge-content ge-content-type-ckeditor" data-ge-content-type="ckeditor"><div class="col-md-4 col-sm-6 text-center margin-bottom-30 col-xs-4 column">
			<div class="ge-content ge-content-type-ckeditor" data-ge-content-type="ckeditor"></div></div></div>`

Many greetings

**Comment by Epskampie** [comment]
That is how it is supposed to work, that way grideditor can correctly edit the content again later. If you dont want rhose classes you can easily remove them using jquery.
