### ISSUE TITLE
Timing issue with TinyMce

### ISSUE THREAD

**Issue by madc** [Frontwise/grid-editor#6]
In some cases, when the tinymce editor takes longer to load, a timing issue can cause the editor to not show up on the first click. Then the user has ti click a second time to make the editor visible.

I resolved this by replacing (L18-L21 in jquery.grideditor.tinymce.js)[https://github.com/Frontwise/grid-editor/blob/master/src/js/jquery.grideditor.tinymce.js#L18-L21] with the following code:

````
var configuration = $.extend(
    (settings.tinymce && settings.tinymce.config ? settings.tinymce.config : {}),
    {
        inline: true,
        oninit: function(editor) { $('#'+editor.settings.id).focus(); }
    }
);
var tiny = contentArea.tinymce(configuration);
````

This makes sure, that the `.focus()` only fires after the editor was initialized. It also enforces `inline:true`, even it it is not set in the grideditor configuration.

I can prepare a pull request, if you see the advantage of this approach.

**Comment by Epskampie** [comment]
Yeah, that does seem like a better approach. Only way I can see this failing if is the user passes in their own `oninit` in `settings`. If you could add a check for that I will gladly merge a PR.
