### ISSUE TITLE
Plan to support bootstrap 4 ?

### ISSUE THREAD

**Issue by brouillon** [Frontwise/grid-editor#62]
Again really thanks for this script !

All is in the title, do you plan to port this project to support bootstrap 4 ?

**Comment by Epskampie** [comment]
Good question. It through I would wait for bootstrap 4 to come out of beta, but it seems like that will not happen soon. 😁

If I'm reading the docs, it seems like the classnames have stayed the same, so it should mostly just work, but without support for all the new flexbox functionality of course. 

https://getbootstrap.com/docs/4.0/layout/grid/

Did you try it with bootstrap 4 yet?

**Comment by AndyPresto** [comment]
Bootstrap 4 has now been released. 

I tried grid-editor with BS4 and found that there's some incompatibility with the new grid system.

![capture](https://user-images.githubusercontent.com/8163146/36307014-10b8463c-1312-11e8-9c05-2282fe22bd78.PNG)

**Comment by Epskampie** [comment]
Bootstrap 4 support is now added! Try it out and let me know how it goes. See [UPGRADING.md](https://github.com/Frontwise/grid-editor/blob/master/UPGRADING.md) for the changes you need to make when upgrading.
