### ISSUE TITLE
Where do you put tinymce.config settings?

### ISSUE THREAD

**Issue by AliasSuperman** [Frontwise/grid-editor#63]
Hi,

Thanks for the script.  

I can't figure out from the readme where tinymce.config settings go such as those below to customise plugins and toolbars:

// Plugins
plugins: [
        'advlist autolink autoresize autosave link image imagetools lists charmap print preview hr anchor pagebreak',
        'searchreplace wordcount visualblocks visualchars code media nonbreaking',
        'table directionality emoticons template paste textcolor colorpicker', 

// Toolbars
toolbar1: "undo redo | bold italic underline strikethrough subscript superscript | formatselect |  fontselect | fontsizeselect | forecolor backcolor | cut copy paste ", //preview
      
toolbar2: "bullist numlist | alignleft aligncenter alignright alignjustify | outdent indent | link unlink image media hr table | charmap emoticons anchor | searchreplace | visualblocks visualchars preview code",

Thanks in advance for any assitance.

**Comment by Epskampie** [comment]
Put it in the initial call to gridEditor({tinymce: { config: { your config here } } } .
