### ISSUE TITLE
toolbar

### ISSUE THREAD

**Issue by ullash099** [Frontwise/grid-editor#64]
please give example of summernote and other toolbar example like:
$('#myGrid').gridEditor({
                new_row_layouts: [[12],[6, 6],[9, 3],[3, 9],[4,4,4],[3,3,3,3]],
                content_types: ['summernote'],
                summernote: {
                    config: {
                        callbacks: {
                            onInit: function() {
                                var element = this;
                            }
                        },
                        toolbar: {
                            // [groupName, [list of button]]
                            style:['bold'],['italic'],['underline'],['clear'],
                            font:['strikethrough'],['superscript'],['subscript'],
                            fontsize:['fontsize'],
                            color:['color'],
                            para:['ul'],['ol'],['paragraph'],
                            height:['height']
                        }
                    }
                }
            });

**Comment by Epskampie** [comment]
Code seems correct. Does it work on a regular summernote? (Without grideditor)
