### ISSUE TITLE
remove editor data

### ISSUE THREAD

**Issue by ang3lx** [Frontwise/grid-editor#67]
Hello i'm testing this editor but when I call $('#myGrid').gridEditor('getHtml'); and show it in log console, I see ckeditor class code. How can have clean grid?

class="ge-content ge-content-type-ckeditor" data-ge-content-type="ckeditor"

![schermata 2018-01-09 alle 19 01 42](https://user-images.githubusercontent.com/1527093/34735386-93b6dc58-f56f-11e7-9426-d21e5e432daa.png)

**Comment by Epskampie** [comment]
That is so that grid-editor know what RTE to use when editing this code later. If you want to remove it you can just use some jquery like `$(htmlString).find('.ge-content-type-ckeditor').removeClass('ge-content-type-ckeditor')` but grideditor wont function correctly anymore on that html.
