### ISSUE TITLE
Support for other RTE

### ISSUE THREAD

**Issue by Dahkon** [Frontwise/grid-editor#69]
Hello,
Very nice tool, is there plans for supporting other RTE or documentation maybe to implement ourself another RTE ?
I would like to integrate your tool in our backend solution but we're using Medium editor as our main RTE and don't want to use another one.
https://yabwe.github.io/medium-editor/

An api with some events might just be enough ?
Thanks,

**Comment by Epskampie** [comment]
No plans, if you follow the example in src/js/jquery.grideditor.tinymce.js it should be easy enough. Please submit a PR if you do!
