### ISSUE TITLE
re-init new tools on injected html code

### ISSUE THREAD

**Issue by ang3lx** [Frontwise/grid-editor#72]
Hello,
i've loaded an html snippet into #myGrid container with this code
<pre>
$.get( "templates/"+$(this).data('template')+".html", function( data ) {
              $( "#myGrid" ).prepend( data );
// init() ????
});
</pre>

is possible to reinit editor to add rows and cols events and tools?

**Comment by Epskampie** [comment]
Use the new `remove` method , and init again later.
