### ISSUE TITLE
Automatically inserts "style='display:block;'" after move

### ISSUE THREAD

**Issue by tmtung144** [Frontwise/grid-editor#73]
This problem occurs when I change the order of arranging blocks for each other, or click the "Move" button then pull out.

Now:
`<div class="row">.....`
change to
`<div class="row" style='display:block;'>.....`

This will cause the bootstrap grid to no longer function.

Sorry for my language limitations!!! Tks !!!

**Comment by Epskampie** [comment]
Sorry, but i cannot reproduce, you will have to explain more clearly. What browser, what exactly are you doing?
