### ISSUE TITLE
Method call on init/deinit custom row/column tools

### ISSUE THREAD

**Issue by fantanamihai** [Frontwise/grid-editor#76]
When creating custom row/column tools I want to have a way (method/event) to call method on init/deinit.
E.g.
```settings: {
    col_tools: [{
       title: 'Set background',
       on: {
           init: function() { .... },
           deinit: function() { ... },
           click: function() { .... }
       }
    }]

**Comment by Epskampie** [comment]
Also, when what is inited? the button?

**Comment by fantanamihai** [comment]
If I want to instantiate a jquery plugin like a color picker
![image](https://user-images.githubusercontent.com/5626860/42319020-00a349c0-8051-11e8-9ef0-fedf43ab8d57.png)

**Comment by Epskampie** [comment]
Why don't you just intialize it on first click?

**Comment by Epskampie** [comment]
And de-init after pick?

**Comment by fantanamihai** [comment]
No. For that we have 'click' right? I don't know if deinit is that important, but I would call it when removing row/column or grideditor.deinit()

**Comment by Epskampie** [comment]
Lets's continue here: #77
