### ISSUE TITLE
 Get resulting html

### ISSUE THREAD

**Issue by Marcel1514** [Frontwise/grid-editor#78]
Thank you ! Great tool 

Using   var html = $('#myGrid').gridEditor('getHtml') to retreive edited content

It seems the editor left some "personnal" code in the Html 

.. class="ge-content ge-content-type-ckeditor" data-ge-content-type="ckeditor" ...

Is it by design ?

**Comment by Epskampie** [comment]
Yes, it needs those to re-initialize the content later. You can use jquery to strip it out if you don't want to use the content again in grid-editor.
