### ISSUE TITLE
Add $ to wrapper functions

### ISSUE THREAD

**Issue by m-schreiber** [Frontwise/grid-editor#89]
I have an issue while using this plugin when jquery is only available as `jquery` and not as `$`.

Working:
https://github.com/Frontwise/grid-editor/blob/12d58dbb459aab44215d41a3dcab29738243d8a3/src/js/jquery.grideditor.js#L4
https://github.com/Frontwise/grid-editor/blob/12d58dbb459aab44215d41a3dcab29738243d8a3/src/js/jquery.grideditor.js#L579

Not Working:
https://github.com/Frontwise/grid-editor/blob/12d58dbb459aab44215d41a3dcab29738243d8a3/src/js/jquery.grideditor.ckeditor.js#L1
https://github.com/Frontwise/grid-editor/blob/12d58dbb459aab44215d41a3dcab29738243d8a3/src/js/jquery.grideditor.ckeditor.js#L74

https://github.com/Frontwise/grid-editor/blob/12d58dbb459aab44215d41a3dcab29738243d8a3/src/js/jquery.grideditor.summernote.js#L1
https://github.com/Frontwise/grid-editor/blob/12d58dbb459aab44215d41a3dcab29738243d8a3/src/js/jquery.grideditor.summernote.js#L67

https://github.com/Frontwise/grid-editor/blob/12d58dbb459aab44215d41a3dcab29738243d8a3/src/js/jquery.grideditor.tinymce.js#L1
https://github.com/Frontwise/grid-editor/blob/12d58dbb459aab44215d41a3dcab29738243d8a3/src/js/jquery.grideditor.tinymce.js#L64

**Comment by Epskampie** [comment]
Good point, could you make a pull request making this change to the RTE integrations? Thanks.

**Comment by Epskampie** [comment]
Fixed in #90
