### ISSUE TITLE
Custom CSS files

### ISSUE THREAD

**Issue by rsuchovsky** [Frontwise/grid-editor#91]
Hi, is it possible to insert css files into your plug-in, just like it is in CkEditore?
Example:

`           CKEDITOR.editorConfig = function( config ) {
                config.contentsCss = [ 
'http://web.sk/mycss.min.css' ,
 'http://web.sk/mycss2.min.css' 
];
            };`

**Comment by Epskampie** [comment]
Yeah, you can pass all ckeditor options, they are simply passed on to ckeditor.

https://github.com/Frontwise/grid-editor#rich-text-editor-options

`ckeditor.config`

**Comment by rsuchovsky** [comment]
Thank you for your reply

The module does not take config from CkEditor for  config.contentsCss , but ignores embedded CSS files

Other config is OK :)

It would be **great** if it zobeire also the CSS file
**Otherwise great work**

![codes](https://user-images.githubusercontent.com/29576358/55421632-f5844180-5579-11e9-838f-b97d3438cb37.PNG)
