### ISSUE TITLE
Issue : source_textarea whith existing data

### ISSUE THREAD

**Issue by Nuranto** [Frontwise/grid-editor#97]
Case : I want to use grid-editor on an existing app, where there is data already.

In some textareas I want to transform, there is only text. In that case, the text is displayed above the grid manager, and cannot be edited or removed which leads to a dead-end....

Solution : add this text in a simple 12-col row...

**Comment by Nuranto** [comment]
Note : I know, I've created many issues...
I can try to PR for some on them... if is this repo is still maintained ?

**Comment by zotalegre** [comment]
Hi Nuranto,
yes, Simon is a busy tech but he does things here. Best way to call him is with some workable code. So, if you start he will show up, I bet ;)

**Comment by Epskampie** [comment]
Hey, yeah, like @zotalegre said this repo is still maintained, but not actively developed. I try to keep things simple, and only add functionality that:

* Is useful to 90% of all users, so only really general stuff for everybody, not for very specific use cases.
* Cannot be done yourself with 2 lines of jQuery. Don't replicate jQuery functionality in the tool.

So keep that in mind if you start working on something. If PR's meet these requirements I'll merge them gladly.

Anyway, thanks for all the ideas, haven't had time to look at them specifically, but with these guidelines you should be OK. For example, the one about keeping source_textarea seems useful, if the performance impact is not too big.

This one seems less useful, I think it's the programmers job to feed the plugin with proper data.

**Comment by Nuranto** [comment]
Ok, I have to say it will be difficult for me to know what could meet these requirements and what couldn't.
For instance, keeping source_textarea updated could be done with 2 lines of jquery too. The issue is 2 lines for this + 2 lines for that + etc... can finally adds a lot of extra lines.
Well, I'll PR each one, and you'll decide :)

**Comment by Epskampie** [comment]
Cool, thanks for your PR's, discussion continues there: #100
